#' s13_games
#'
#' TPL season 13 game summary data
#'
#' @format ## `s13_games`
#' A data frame 75 rows and 14 columns
#' @source <https://tplapp.onrender.com/games/574>
"s13_games"

#' s14_games
#'
#' TPL season 14 game summary data
#'
#' @format ## `s14_games`
#' A data frame 84 rows and 14 columns
#' @source <https://tplapp.onrender.com/games/596>
"s14_games"

#' s15_games
#'
#' TPL season 15 game summary data
#'
#' @format ## `s15_games`
#' A data frame 77 rows and 14 columns
#' @source <https://tplapp.onrender.com/games/629>
"s15_games"

#' s16_games
#'
#' TPL season 16 game summary data
#'
#' @format ## `s13_games`
#' A data frame 30 rows and 14 columns
#' @source <https://tplapp.onrender.com/games/652>
"s16_games"

#' s17_games
#'
#' TPL season 17 game summary data
#'
#' @format ## `s13_games`
#' A data frame 36 rows and 14 columns
#' @source <https://tplapp.onrender.com/games/694>
"s17_games"

#' s18_games
#'
#' TPL season 18 game summary data
#'
#' @format ## `s18_games`
#' A data frame 52 rows and 14 columns
#' @source <https://tplapp.onrender.com/games/703>
"s18_games"

#' s19_games
#'
#' TPL season 19 game summary data
#'
#' @format ## `s19_games`
#' A data frame 65 rows and 14 columns
#' @source <https://tplapp.onrender.com/games/728>
"s19_games"

#' s20_games
#'
#' TPL season 20 game summary data
#'
#' @format ## `s20_games`
#' A data frame 70 rows and 14 columns
#' @source <https://tplapp.onrender.com/games/739>
"s20_games"

#' s19_players
#'
#' A list of all season 19 players with general info
#'
#' @format ## `s19_games`
#' A data frame 134 rows and 5 columns
#' @source Generated manually from S19 draft spreadsheet
"s19_players"

#' s20_players
#'
#' A list of all season 20 players with general info
#'
#' @format ## `s20_games`
#' A data frame 114 rows and 5 columns
#' @source Generated manually from S20 draft spreadsheet
"s20_players"


#' s21_players
#'
#' A list of all season 20 players with general info
#'
#' @format ## `s21_games`
#' A data frame 126 rows and 1 columns
#' @source Generated manually from S21 draft spreadsheet
"s21_players"

#' historical_boxscores
#'
#' Boxscore and plus/minus data for previous TPL seasons
#'
#' @format ## `historical_boxscores`
#' A data frame 13212 rows and 33 columns
#' @source Generated by calling `generate_box_scores()` on all historical games
"historical_boxscores"

#' historical_possessions
#'
#' Detailed possession level data for previous TPL seasons
#'
#' @format ## `historical_possessions`
#' A data frame 166304 rows and 13 columns
#' @source Generated by calling `create_detailed_possessions()` on all historical games
"historical_possessions"

#' s21_game_IDs
#'
#' A list of s21 games with game and team IDs
#'
#' @format ## `s21_game_IDs`
#' A data frame 50 rows and 3 columns
#' @source Generated manually by Viv
"s21_game_IDs"

#' s21_boxscores
#'
#' TPL season 21 boxscore data
#'
#' @format ## `s21_boxscores`
#' A data frame 1389 rows and 14 columns
#' @source Generated by Viv using <https://tplapp.onrender.com/games/764>
"s21_boxscores"
